package org.vniizht.suburbsweb.model.transformation.level3.tables;

import lombok.Getter;
import lombok.Setter;

import javax.persistence.Entity;
import javax.persistence.Table;
import java.sql.Date;

@Entity
@Table(name = "prig_work")
@Getter
@Setter
public class Work {
    private short           rez;
    private long            opis;
    private long            idnum;
    private int             request_num;
    private short           yymm;
    private int             k_bil;
    private int             nom_mar;
    private int             nom_bil;
    private int             nom_dat;
    private Date            date_zap;
    private String          time_zap;
    private String          server_reqnum;
    private String          drac;
    private int             part_zap;
    private Date            date_beg;
    private Date            date_end;
    private Date            date_pr;
    private char            term_dor;
    private String          term_pos;
    private String          term_trm;
    private short           agent;
    private short           subagent;
    private short           chp;
    private int             stp;
    private short           stp_reg;
    private int             kol_bil;
    private long            plata;
    private long            poteri;
    private long            perebor;
    private long            nedobor;
    private long            kom_sbor;
    private long            kom_sbor_vz;
    private short           k_pas;
    private short           srok_bil;
    private short           srok_mon;
    private char            oper;
    private char            oper_g;
    private char            flg_bag;
    private char            flg_tuda_obr;
    private char            flg_rab_day;
    private char            flg_ruch;
    private char            vid_rasch;
    private char            flg_child;
    private short           flg_voin;
    private char            flg_military;
    private char            flg_lgt;
    private char            flg_bsp;
    private char            flg_so;
    private char            flg_nu;
    private char            flg_tt;
    private String          klass;
    private short           kod_lgt;
    private short           lgt_reg;
    private char            bag_vid;
    private short           bag_ves;
    private short           proc_lgt;
    private char            rzd_fpk;
    private String          abonement_type;
    private char            abonement_subtype;
    private char            flg_official_benefit;
    private char            train_category;
    private String          train_num;
    private char            employee_cat;
    private String          flg_sbor;
    private char            flg_bil_sbor;
    private short           request_type;
    private short           request_subtype;
    private String          web_id;
    private char            prod;
    private short           plus_dat;
    private short           kpas_day;
    private int             sto;
    private int             stn;
    private short           srasst;
    private short           sto_zone;
    private short           stn_zone;
    private int             sti;
    private short           sti_zone;
    private short           sto_reg;
    private short           stn_reg;
    private short           nom;
    private short           reg;
    private int             marshr;
    private int             st1;
    private int             st2;
    private short           rst;
    private short           dor;
    private short           lin;
    private short           mcd;
    private long            d_plata;
    private long            d_poteri;
    private short           otd;
    private short           dcs;
    private String          fio;
    private String          fio_2;
    private String          snils;
    private String          ticket;
    private String          kodbl;
    private String          benefit_doc;
    private String          benefit_podr;
    private String          bilgroup;

}
